org-roam-bibtex.el
Provide function to handle the note-cookie in `helm-bibtex` and `ivy-bibtex`.
Now, when `org-roam-bibtex-mode` is activated, `helm-bibtex` will show that an entry has a note if there exists an Org-roam bibliographic note for it.
I was waiting on a merge from upstream before finishing the work on this branch.
=> Handle note cookie in bibtex-completion

org-roam-bibtex-note-actions.el, org-roam-bibtex.el
@zaeph Here is a small library with one main function `org-roam-bibtex-note-action`, which when called interactively will present a user with some actions related to the notes file. Currently, there are not too many actions offered - open PDF, open DOI/URL, add PDF, show BibTeX entry. But the basic framework is here, I believe, and it supports `ivy`, `helm`, `ido` and `hydra` besides the default `completing-read`. I haven't tested it well, a feedback is greatly appreciated.
=> org-roam-bibtex-note-actions first commit

README.md, orb-compat.el, orb-note-actions.el, org-roam-bibtex.el
As discussed in #23, the namespace `org-roam-bibtex` is renamed into `orb`. The main file `org-roam-bibtex.el` retains its name, all other libraries are prefixed with `orb-`.
=> rename namespace org-roam-bibtex>orb; v0.2

org-roam-bibtex.el
We need to require `orb-note-actions` in `org-roam-bibtex.el`.  Otherwise, `autoload` commands are not set.
=> Require orb-note-actions

README.md
67c8d2ee01dc11a51f6586088692b405f5e6bfc9 set a new default for `org-roam-bibtex-preformat-keywords`, but we forgot to update the doc.
=> Change ‘=key=’ with ‘citekey’ in doc

orb-note-actions.el, org-roam-bibtex.el
This reverts commit f0a65ae9b9fd779835dbea2b5ebfa40657f7d209.
Follows from the discussion in #13.
=> Revert "Require orb-note-actions"

orb-note-actions.el
A new note action: save current note's citekey to kill-ring and clipboard.
=> add save citekey note action

README.md, org-roam-bibtex.el
Someone on Slack ran into a problem with one of the examples on the `README.me`:
https://github.com/org-roam/org-roam-bibtex/blob/850c238b2f36ac73e600937e7851c1f36defbe0f/README.md#L249-L250
`citekey` does not preformat `=key=` because it has no knowledge of it.  I've considered solving this problem by validating `orb-preformat-keywords` and `push`ing `=key=` if it didn't exist, but I didn't like the way it looked.  So, I've elected to raise an error instead.  I think it should be sufficiently informative:
> No preformating found for ‘=key=’.  Please adjust ‘orb-preformat-keywords’
=> Raise error if =key= is not preformated in orb-preformat-keywords

org-roam-bibtex.el
This is to address the changes made from alists to hash-lists upstream to get the tags working.  We're about to move move force modern completion-engines, so this PR might get adjusted soon.
=> Fix non-ref find-file/insert

orb-core.el, orb-note-actions.el, orb-utils.el, org-roam-bibtex.el
A continuation of thoughts expressed in #13 
1) `orb-core.el` as a central dependency point. It requires `org-roam` and `bibtex-completion`. It is supposed to be required by user interface libraries. It contains `defgroup` definitions and general utility functions that depend on `org-roam`, `bibtex-completion` and other packages not included in Emacs. It itself does not require any user interface libraries but may require utility libraries.
2) `orb-utils.el` - general purpose utilities that do not depend on extra packages, only built-in Emacs libraries (an exception can be made for general purpose extra libraries such as `dash`, `f`, `s`). If a function requires anything from `org-roam`, `bibtex-comletion` or other specialized libraries, it should go into `orb-core.el` or a specialized …
=> Redesign structure of org-roam-bibtex package

README.md
- leaving it out may potentially lead to loading problems #66
=> docs: :after org-roam in use-package examples

orb-core.el, orb-note-actions.el, org-roam-bibtex.el
Since `org-roam` as of v1.2.0 does not require `org-ref` upon start-up, we declare the functions used from `org-ref` (we previously relied on `org-roam` requiring `org-ref`).
Also,
https://github.com/hlissner/doom-emacs/pull/2888
Use `declare-function` to declare a couple of `bibtex-completion` functions instead of top-level ` (require 'bibtex-completion)` .
=> do not require bibtex-completion

org-roam-bibtex.el
wrap the buggy `bibtex-completin-apa-get-value` in a`condition-case`
to silently return "" if the former throws an error
Temporary workaround until fixed upstream
=> hotfix #83

org-roam-bibtex.el
Fixes #86.
Removing the hook seems to do the trick, since we've changed the way we hook onto `org-capture` in org-roam/org-roam/pull/966.
=> Remove hook based on upstream change

org-roam-bibtex.el
Org-roam allows its users to set a custom function to convert a title to the filename slug.
See https://github.com/org-roam/org-roam/pull/833.
=> Respect user set org-roam-title-to-slug-function

README.md, orb-core.el, org-roam-bibtex.el
- `orb-process-file-field` can filter the retrieved file names based on a particular
extension
- `orb-file-field-extensions` controls which extensions to match
- `orb-process-file-keyword` controls special treatment of %^{file} and
${file} wildcards during the template expansion
Addresses #98.
=> improve orb-process-file-field

org-roam-bibtex.el
- take the possibility into account that `org-roam-capture-function` may
be other than `org-capture`
=> (int,fix) pre-select a capture template

README.md, orb-core.el, orb-utils.el, org-roam-bibtex.el
New command `orb-insert`: similar to `org-roam-insert` but for BibTeX notes.
This commit also adds a functionality to ease managing of `org-capture` hooks when calling `orb-edit-notes`.  This is now only used to support `orb-insert` but the functionality is appropriate for general use. Similarly, `orb-plist` and getter and setter functions have been added, which may be used anywhere else within `org-roam-bibtex`; and a few other utilities.
<details>
<summary>New functionality</summary>
- orb-insert
- orb-insert-frontend
- orb-insert-link-description
- orb-insert-generic-candidates-format
- orb-edit-notes-note-exists-hook
- orb-insert-edit-notes
- orb-insert-generic
- orb-register-hook-function
- orb-do-hook-functions
- orb-call-hook-function
- orb-cleanup-hooks
- orb-get-buffer-keyword
- …
=> orb-insert first commit

CHANGELOG.md, README.md, orb-anystyle.el, orb-compat.el, orb-core.el, orb-note-actions.el, orb-pdf-scrapper.el, orb-utils.el, org-roam-bibtex.el
- update the version number
- update the Changelog
- update keybindings in the README
- use package keywords from the `finder-by-keyword` list
- remove version numbers and keywords from files other
than `org-roam-bibtex.el`
=> bump to version 0.4.0

org-roam-bibtex.el
- Do not run `org-capture-select-template` if only one template is
defined - use the template immediately.
fix #124
=> (fix) when only one template is defined, use it

README.md, orb-anystyle.el, orb-compat.el, orb-core.el, orb-helm.el, orb-ivy.el, orb-pdf-scrapper.el, orb-utils.el, org-roam-bibtex.el
- point users ot gnu.org for a license
- rename orb-insert-frontend into orb-insert-interface,
orb-note-actions-frontend into orb-note-actions-interface
- make the old fanctions obsolete
- remove old compatibility declarations
=> (int,doc) update license instructions

README.md, orb-core.el, orb-pdf-scrapper.el, org-roam-bibtex.el
- Rename `orb--virtual-fields-alist` to `orb-bibtex-field-aliases` and
make it a user option.
- Simplify field mapping: `orb-preformat-keywords` now only supports a
list of template keywords. String and cons cell types are not supported.
Field mapping is fully delegated to `orb-bibtex-field-aliases`.  As a
consequence, remove the unused function `orb--replace-virtual-fields`.
=> (feat,int) orb-bibtex-field-aliases

orb-core.el
don't fail if pdf file is empy, or bibtex-completion-find-pdf throws an error.
See https://org-roam.discourse.group/t/issues-with-org-roam-bibtex/1046/11
=> (fix) orb-process-file-field

orb-utils.el, org-roam-bibtex.el
To greatly speed up things when bibtex-completion builds its cache
Fix #156
`orb-find-note-file` now does not have a visible impact on `bibtex-completion-parse-bibliography` (master bib file with ~1800 entries):
1 run with the old function: ~15.5 s
1 run with the fixed function: ~2.9 s
1 run without using `orb-find-note-file`: ~2.9 s
1 run with `orb-find-note-file` + default functions: ~3.1 s
This simple test was used:
```elisp
(benchmark-run 5
(progn
(setq orb-notes-cache nil
bibtex-completion-cache nil)
(bibtex-completion-candidates)))
```
| fix | value of `bibtex-completion-find-note-functions | total time, s | GC runs | GC time |
| --- | --- | --- | --- | --- |
| no | '(orb-find-note-file) | 77.518197 | 420 | 44.164464 |
|  yes | '(orb-find-note-file) |  14.664627 | 62 | …
=> (fix) orb-notes-cache for orb-find-note-file

orb-utils.el
I've been having problems properly loading `org-roam-bibtex` and `org-ref`; one symptom is that `orb-find-note-file` was
being called before `orb-notes-cache` was initialized, and it seems like a lazy initialization would make
`orb-find-note-file` more robust.
=> Initialize org-notes-cache lazily on demand

orb-core.el
currently org-roam-bibtex will insert the absolute file path as is from bib file.
for eg, it's something like this with my current orb template:
```
:NOTER_DOCUMENT: /Users/emacsbliss/Zotero/storage/SV96UAIW/how-javascript-works-the-mechanics-of-web-push-notifications-290176c5c55d.html
```
However the issue is when I switch to different computer (for eg, company one) where I don't have control with username, then org-noter will break because user name is different even though Zotero is installed on same location (ie. ~/Zotero) on both machine.
I think it would make sense to insert abbreviate file path so it will work on different machines with different username as long as Zotero is under same location relative to user home directory.
With this PR, it will insert this:
``` …
```
=> abbreviate file path

orb-pdf-scrapper.el
also ix the default value of `orb-pdf-scrapper-export-options`
=> (fix) scrapper error when cit. number is nil

CHANGELOG.md, README.md, org-roam-bibtex.el
Remove keybindings in `org-roam-bibtex-mode-map`.  The chosen key prefix
conflicts with other modes, e.g. RefTeX.  Also, the `orb-note-actions`
command is conceptually a local command and will not work in non-Org
Roam buffers and other modes.  See #182 for a discussion.
=> (int,fix) remove default keybindings

CHANGELOG.md, orb-core.el, orb-utils.el
issue a warning in orb-process-file-field instead of ignoring errors
silently
=> (fix) issue a warning in orb-process-file-field

README.md
The channel has already been moved and populated, but the changes have not been reflected in the README as of now.
=> Change from Freenode to Libera Chat

org-roam-bibtex.el
Org-roam upstream renamed :if-new key to :target in
org-roam-capture-tempates.  The former can still be used but will be
dropped eventually.  Allow for both keys.
Fixes #209
=> (fix) Account for :if-new renamed to :target

org-roam-bibtex.el
`orb-edit-notes` can accept a list of strings or a list of lists whose
element lists start with strings.
See #211.
@bdarcus On another thought I decided to not modify `orb-edit-note`. By design, it accepts a single argument, a citation key as string, and should probably stay as such. It would anyway require additional destructuring because plain `(defun orb-edit-note (citekey &optional entry)` would not work because (KEY . ENTRY) is still a single argument. 
I instead modified the function `orb-edit-notes`, which is meant to be plugged in into `bibtex-completion-edit-notes-function` or `bibtex-actions-file-open-note-function`. This function used to accept a list of keys as returned by `bibtex-comletion`. Now it also accepts a list of lists to support `bibtex-actions`. Note the function …
=> (int) Bibtex-actions support

doc/orb-manual.org
Added line clarifies that src block below shows content of template
=> Add missing line in manual

doc/orb-manual.org, orb-core.el, org-roam-bibtex.el
- Support s-format template wildcards in `orb-insert-link-description`
- New helper function `orb-resolve-field-alias`
=> (feat) wildcards for `orb-insert-link-description`

org-roam-bibtex.el
New function `orb-open-associated-note` according with https://github.com/org-roam/org-roam-bibtex/issues/191#issuecomment-1011875176
=> New function orb-open-associated-note

orb-utils.el, org-roam-bibtex.el
`bibtex-completion-format-entry` fails if `bibtex-completion-display-formats-internal` is `nil`, which is the case if bibtex completion has not been initialized via `(bibtex-completion-init)` and I run `orb-note-actions`.
This happened to me because I install `bibtex-completion` via `straight.el` without `helm-bibtex` or `ivy-bibtex`. Calling commands of either of those packages seems to initialize it. When it is not initialized, that resulted in the error message
s-format: Wrong type argument: arrayp, nil
because `bibtex-completion-format-entry` then tries to format a `nil` string.
Calling `(bibtex-completion-init)` seems to be cheap after subsequent invocations, but I'm not sure that calling it in every `orb-format-entry` is the best solution or we can somehow make sure to call it only …
=> Ensure bibtex-completion is initialized

orb-section.el, orb-utils.el
Sections are:
- `orb-section-reference` which shows a formatted reference.
- `orb-section-abstract` which shows the abstract.
- `orb-section-file` which provides a link to the file.
=> add three initial org-roam-mode-buffer sections for orb

org-roam-bibtex.el
This PR sets the required version of `bibtex-completion` from 2.0.0 to 1.0.0, since version 2.0.0 does not exist as far as i can tell and the wrong version requirement causes problems (see https://github.com/progfolio/elpaca/issues/263).
=> Set required bibtex-completion version to 1.0.0
