org-roam/org-roam-bibtex

org-roam-bibtex.el

Rejected for `org-roam` (jethrokuan/org-roam#481), but might be convenient for BibTeX users.
Upstream merge for jethrokuan/org-roam#481 is required.

Implement functions/commands for filtering find-file and insert

---

README.md
org-roam-bibtex.el

Fixes #16.
@myshevchuk Can you think of any problem that'd come with that change?

Preserve case in citekey rather than slugging it

---

README.md

Will help with orb-note-actions discoverability.

Add key-binding for orb-note-actions in default config

---

org-roam-bibtex.el

Fixes #32.
Waiting for jethrokuan/org-roam/pull/567 to be merged.

Update find-ref for upstream change

---

CHANGELOG.md
README.md
orb-compat.el
orb-note-actions.el
org-roam-bibtex.el

add changelog, bump to v0.2.2

---

org-roam-bibtex.el

Implement orb--virtual-fields-replacements

---

orb-compat.el
orb-macs.el
orb-note-actions.el
org-roam-bibtex.el

- /s/orb--unformat-citekey/orb-unformat-citekey
- move orb-unformat-citekey to orb-macs

helper file orb-macs

---

org-roam-bibtex.el

Fix orb-find-note-file

---

orb-note-actions.el

Hotfix #55

---

org-roam-bibtex.el

I’m in the middle of a break to focus on writing, so feel free to merge to this for me.

Add ‘date’ to list of preformat-keywords

---

org-roam-bibtex.el

cf. https://github.com/jethrokuan/org-roam/blob/ad5fca5440e5c8a6b8078013684df43b3e43d773/org-roam-compat.el#L78-L79

Replace deprecated function

---

orb-compat.el
orb-core.el
orb-note-actions.el
orb-utils.el
org-roam-bibtex.el

set file local fill-column to 79

---

README.md
orb-note-actions.el

- also make `orb-note-actions-default` a user variable

Add note actions documentation

---

org-roam-bibtex.el

Linked to org-roam/org-roam/pull/908.

Update find-non-ref to new upstream schemata

---

orb-anystyle.el
orb-pdf-scrapper.el

- anystyle requires absolute file paths, ensure it's happy
- improve training session messages

file-truename for anystyle input and output

---

README.md

Fix broken a link to Spacemacs instructions

---

org-roam-bibtex.el

Remove org-roam--with-template-error

Upstream follow-up

---

org-roam-bibtex.el

Org Ref defines the function `org-ref-bibtex-store-link' to store links to a BibTeX buffer, e.g. with `org-store-link'.  At the same time, Org ref requires `ol-bibtex' library, which defines `org-bibtex-store-link' to do the same.  When creating a note with `orb-edit-notes' from a BibTeX buffer, for example by calling `org-ref-open-bibtex-notes', the initiated `org-capture' process implicitly calls `org-store-link'.  The latter loops through all the functions for storing links, and if more than one function can store links to the location, the BibTeX buffer in this particular case, the user will be prompted to choose one.  This is definitely annoying, hence ORB will advise all functions in `orb-ignore-bibtex-store-link-functions` to return nil to trick `org-capture' and get rid of the …

orb-ignore-bibtex-store-link-functions

---

org-roam-bibtex.el

- `orb-use-as-slug` allows to specify what piece of
information should be used to create a slug identifier.
Possible values are symbols `citekey` or `slug`.
- `orb-edit-notes` was adjusted to support this.
Addresses #106

orb-use-as-slug

---

org-roam-bibtex.el

orb-edit-notes. nil field values as empty strings

---

org-roam-bibtex.el

Let the user select a capture template before the capture process has started and work with it.
fix #10

Pre-select org-capture template

---

CHANGELOG.md

(doc) credits to garrettdreyfus

---

org-roam-bibtex.el

(fix) catching bugs after refactoring

---

org-roam-bibtex.el

(bug) fix typo in `orb-edit-notes`

---

README.md
org-roam-bibtex.el

- Suggest what could be the reason the citation key was not retrieved
- Add README section about dependencies
See #127.

(doc,int) improve orb-note-actions error message

---

orb-pdf-scrapper.el

A user option to control whether a prompt about generating keys should
be presented after finishing edits in the BibTeX buffer
Addresses #161

(feat) orb-pdf-scrapper-prompt-to-generate-keys

---

orb-core.el

(fix) respect orb-file-field-extensions

---

README.md

Maintenance badge should link to same project

---

org-roam-bibtex.el

also signal errors in orb-edit-notes

(int) compat. with old orb-preformat-keywords

---

org-roam-bibtex.el

Allow for debugging.  This won't work in many cases because
`org-capture` process has `condition-case` wrappers.

(int) improve error reporting in orb-edit-notes

---

org-roam-bibtex.el

- add `org-ref` in Package-Requires

(int) package version 0.5.0

---

org-roam-bibtex.el

Rename bibtex-actions to citar

---

orb-helm.el
orb-ivy.el
orb-utils.el
org-roam-bibtex.el

Fix incompatibilities with Org-ref v3

---

doc/orb-manual.org
orb-compat.el
orb-utils.el
org-roam-bibtex.el

Fix Org-cite format in the `orb-roam-ref-format` option

---

org-roam-bibtex.el

Support bibtex-completion’s key-at-point

---

README.md

Simple fix to the README to further minimise the chance that you feel the need to be rude to someone that is just asking for help.

Changed the Doom command to allow unpinning

---

README.md

[Doc-fix] Clarify needed configuration for integration with Citar
